sudo: true
os: linux
cache: false
language: ruby
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
branches:
  only:
    - master
    - QA
    - /^feature.*$/
before_install:
  - openssl aes-256-cbc -K $encrypted_63032c925c2f_key -iv $encrypted_63032c925c2f_iv
    -in assets/server.key.enc -out assets/server.key -d
  - export SFDX_AUTOUPDATE_DISABLE=false
  - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
  - export SFDX_DOMAIN_RETRY=300
  - export SFDX_DISABLE_APP_HUB=true
  - export SFDX_LOG_LEVEL=DEBUG
  - mkdir sfdx
  - wget -qO- $URL | tar xJ -C sfdx --strip-components 1
  - "./sfdx/install"
  - export PATH=./sfdx/$(pwd):$PATH
  - sfdx --version
  - sfdx plugins --core

jobs:
  include:
    - stage: "Test"                # naming the Tests stage
      name: "Running Tests in Test Environment"            # names the first Tests stage job
      script:
      - sfdx --version
      - sfdx force:auth:jwt:grant --clientid $TEST_CONSUMERKEY --jwtkeyfile assets/server.key --username $TEST_USER --setdefaultdevhubusername -a TestOrg
      - sfdx --version
      - sfdx force:org:list
    - script:
      - sfdx force:auth:jwt:grant --clientid $QA_CONSUMERKEY --jwtkeyfile assets/server.key --username $QA_USER --setdefaultdevhubusername -a QaOrg
      - sfdx --version
      - sfdx force:org:list
      name: "Running Test in QA Environment"     # names the second Tests stage job
      if: branch = QA
    - stage: deploy
      if: branch = QA
      name: "Deploying"
      script:
      - sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $PRODUCTION_USER --setdefaultdevhubusername -a ProductionOrg
      - sfdx --version
      - sfdx force:org:list