sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
branches:
  only:
    - master
    - QA
    - /^feature.*$/
before_install:
- openssl aes-256-cbc -K $encrypted_63032c925c2f_key -iv $encrypted_63032c925c2f_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
stages:
  - name: test
    if: branch = /^feature.*$/
    script:
    - sfdx force
  - name: qa
    if: branch = QA
    script:
    - sfdx force:org:list
  - name: deploy
    if: branch = master
    script: 
    - sfdx force